-- Run this in Supabase SQL Editor (supabase.com → your project → SQL Editor)

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text not null,
  category text not null,
  price numeric(10,2) not null,
  old_price numeric(10,2),
  unit text not null default 'per tablet',
  stock integer not null default 100,
  rx boolean not null default false,
  emoji text not null default '💊',
  desc text not null default '',
  rating numeric(2,1) not null default 4.5,
  reviews integer not null default 0,
  badge text,
  tags text,
  created_at timestamptz default now()
);

-- Allow public read
alter table products enable row level security;
create policy "public can read products" on products for select using (true);
create policy "public can insert products" on products for insert with check (true);
create policy "public can update products" on products for update using (true);
create policy "public can delete products" on products for delete using (true);
